FROM resin/%%RESIN_MACHINE_NAME%%-python

RUN apt-get update && apt-get install -yq \
    git \
    nano \
    curl \
    tk-devel \
    python-tk \
    python-dev \
    python-imaging

RUN pip install RPi.GPIO Pillow

WORKDIR /usr/src/app
COPY . ./
RUN apt-get clean && rm -rf /var/lib/apt/lists/*
CMD ["python2","/usr/src/app/main.py"]
